### ISSUE TITLE
improving performance on ARM devices

### ISSUE THREAD

**Issue by NenuSB** [ShiromMakkad/LedFxDocker#24]
I found performance very poor on Raspberry Pi3B, Nanopi Neo3 and NanopiR4S. After a few minutes the animation would lag severely behind the audio (Squeezebox/LMS). After longer times (10 min or so), when the audio was stopped, the animation would continue for several more seconds.
Testing more extensively on the R4S running Armbian and docker, I found that running the container 'privileged' strongly improves performance. Limiting to specific CPU's also seems to help. This is my adjusted compose file:

```
--------------------------------------
version: '2'

services:
  ledfx:
    image: shirom/ledfx
    container_name: ledfx
    environment: 
      - FORMAT=-r 44100 -f S16_LE -c 2
      - SQUEEZE=1
    ports:
      - 8888:8888
    network_mode: host
    volumes:
      - ./ledfx-config:/app/ledfx-config
      - ~/audio:/app/audio
    cpuset: '4,5'
    privileged: true

--------------------------------------
```

in non-privileged mode, the performance was 'best' (but still very poor) when limiting to only 1 CPU.
With the compose above, it is now running OK for 7 WLED devices with about 1500 pixels in total.
